apiVersion : apps/v1
kind: Deployment
metadata:
  name: githubweb1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubweb1
  template:
    metadata:
      labels:
        app: githubweb1 
    spec:
      containers:
        - name: githubweb1 
          image: registry7967.azurecr.io/githubweb1
          ports:
          - containerPort: 80